### ISSUE TITLE
API - Implement Salesforce Composite API

### ISSUE THREAD

**Issue by AMAN-BARBARIA** [TrueSparrowSystems/AI-SalesSparrow-API#11]
**Goal:** Implement a library to allow Salesforce composite API requests. This lib should also manage the Salesforce access token, refreshing it as necessary.

**Background:** Different Salesforce actions can be performed via the composite API. It also allows us to perform multipleSalesforce operations in a single transaction. This lib would be used from services of various endpoint.

**Tasks:**
- [x] Implement a lib to handle Salesforce composite requests.
- [x] The lib should add the current Salesforce access token to the request before sending it.
- [x] If a request fails due to an expired access token, the endpoint should automatically refresh the token and retry the request once.
- [x] Implement error handling for other error cases, such as invalid requests or server errors.
- [x] Write tests for the library including tests of the token refresh handling.

**Comment by AMAN-BARBARIA** [comment]
This task is required for the completion of user story:
- TrueSparrowSystems/AI-SalesBridge-iOS-App#8
- TrueSparrowSystems/AI-SalesBridge-iOS-App#11

**Comment by AMAN-BARBARIA** [comment]
We can make use of Interceptor Pattern to reuse the common code. eg: 
- Fetch Access Token
- Decrypt with KMS
- Exception Handling
- Handle oauth access token Expiry: refresh token and retry salesforce api
