### ISSUE TITLE
API - Get Content Notes of an Account Endpoint

### ISSUE THREAD

**Issue by AMAN-BARBARIA** [TrueSparrowSystems/AI-SalesSparrow-API#12]
**Goal:** Implement an API endpoint to fetch a list of content notes associated with a particular Salesforce account sorted by last creation time. This endpoint should handle Salesforce access token lifecycle, refreshing it as necessary.

**Background:** For our Salesforce integration, we need to fetch and display the content notes associated with specific accounts. Salesforce access tokens have a limited lifespan, so our implementation needs to handle token expiration and refresh.

**Tasks:**
- [x] Implement a new API endpoint to fetch content notes from Salesforce.
- [x] The endpoint should add the current Salesforce access token to the request before sending it.
- [x] If a request fails due to an expired access token, the endpoint should automatically refresh the token and retry the request once.
- [x] Implement error handling for other error cases, such as invalid requests or server errors.
- [x] Write tests for the new endpoint

**Comment by AMAN-BARBARIA** [comment]
This task is required for the completion of user story TrueSparrowSystems/AI-SalesBridge-iOS-App#4

**Comment by AMAN-BARBARIA** [comment]
We can make use of Interceptor Pattern to reuse the common code. eg: 
- Fetch Access Token
- Decrypt with KMS
- Exception Handling
- Handle oauth access token Expiry: refresh token and retry salesforce api
