### ISSUE TITLE
API - Get Recommended Actions from Text Endpoint

### ISSUE THREAD

**Issue by AMAN-BARBARIA** [TrueSparrowSystems/AI-SalesSparrow-API#13]
**Goal:** Implement an API endpoint to receive a text input and return a list of recommended salesforce actions based on that text.

**Background:** We need an endpoint that can process text and generate recommended actions. This would be used to suggest actions to a user based on the notes added by him

**Tasks:**
- [x] POC on openAI models needs to be done for this use case. 
- [x] Add open api specification
- [x] Implement sequence diagram
- [x] Write tests for the new endpoint.
- [x] Implement the code as per the sequence diagram. 
- [x] Include the endpoint in the postman collection.
- [x] Handle possible errors such as invalid input or server errors.

**Comment by AMAN-BARBARIA** [comment]
This task is required for the completion of user story:
1. TrueSparrowSystems/AI-SalesBridge-iOS-App#8
2. TrueSparrowSystems/AI-SalesBridge-iOS-App#11
